### ISSUE TITLE
Segfaults in herbpy

### ISSUE THREAD

**Issue by mklingen** [personalrobotics/or_interactivemarker#2]
I do the following

    rosrun herbpy console --sim
    env.SetViewer('InteractiveMarker openrave_interactivemarker')

And I get

    Segmentation fault

Also happens when I do
    
    rosrun herbpy console --sim
    view = openravepy.RaveCreateViewer(env, 'InteractiveMarker openrave_interactivemarker')
    view.main(True)

**Comment by mkoval** [comment]
The warnings you are getting from QtCoin are an issue with OpenRAVE. I get three different types of behavior (works with no warnings, warnings and works, warnings and doesn't work) depending upon which computer I use.

I think it depends on which versions of ASSIMP is installed (standard Ubuntu vs. Rosen's PPA vs. the version shipped with OpenRAVE). In any case, I am closing the issue because it's not related to or_interactivemarker. You're welcome to open a new issue on herb_description if you want me to look into it further.
